<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Tweet Away</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $("refreshFeed").click(function(){
                $.load("/feed", function(data){
                    // Display the returned data in browser
                    $("#chatbox").html(data);
                });
            });
            $("#chatbox").load("/feed");
        });
    </script>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }
        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
        .box{
            margin-left: 20%;
            margin-right: 20%;
            padding: 15px;
            text-align: left;
            /* border: 1px solid black; */
        }
        textarea{
            text-align: left;
            padding: 5px;
        }
        #chatbox {
            text-align:left;
            margin:0 auto;
            margin-bottom:25px;
            padding:10px;
            background:#fff;
            height:270px;
            width:900px;
            border:1px solid #ACD8F0;
            overflow:auto; }
        #usermsg {
            width:300px;
            border:1px solid #ACD8F0;
            height:170px; }
    </style>
</head>
<body>
<img src="tweetaway.png" height="220" width="260"/>
<h1>Tweet Away</h1>
<div><h2>A web social media application to waste away time!<h2></div>
<br>
<?php if (isset($name)) : ?>
    <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
<?php else: ?>
    <div class="box">
        <h3>FEED/POST</h3>
        <div id="chatbox">
        </div>
        <button type="button" id="refreshFeed">Refresh</button>
        <h3>Please enter your username and message</h3>

        <form name="message" action="" method="POST">
            Username: <input name="user" type="text" size="30"><br><br>
            Message: <input name="usermsg" type="text" id="usermsg" size="5" /><br><br><br>
            <input name="submitmsg" type="submit"  id="submitmsg" value="Send" />
        </form>

        <br><br>
    </div>
<?php endif; ?>
</body>
</html>